spring:
  application:
    name: task-management
  flyway:
    locations: classpath:/db/migration
    schemas: tasks
    baselineOnMigrate: true
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taskmanager-postgres
    username: postgres
    password: Selim03Kocak09!
  jpa:
    show-sql: true
