spring:
  application:
    name: task-management
  flyway:
    locations: classpath:/db/migration
    schemas: tasks
    baselineOnMigrate: true
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tasks?currentSchema=tasks
    username: postgres
    password: postgres
  jpa:
    show-sql: true
